apiVersion: apps/v1
kind: Deployment
metadata:
  name: pod-reporter
  labels:
    app: pod-reporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-reporter
  template:
    metadata:
      labels:
        app: pod-reporter
    spec:
      containers:
        - name: pod-reporter
          image: 965106989073.dkr.ecr.us-west-2.amazonaws.com/flink:v4.0
          ports:
            - containerPort: 8080
      serviceAccountName: spark
---
apiVersion: v1
kind: Service
metadata:
  name: pod-reporter-service
spec:
  selector:
    app: pod-reporter
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: LoadBalancer
